<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-05-26T20:39:16 IST" name="Instagram Test Suite" finished-at="2025-05-26T20:39:34 IST" duration-ms="18329">
    <groups>
    </groups>
    <test started-at="2025-05-26T20:39:16 IST" name="Login Tests" finished-at="2025-05-26T20:39:34 IST" duration-ms="18329">
      <class name="com.QAproject.loginTest.LoginTest">
        <test-method is-config="true" signature="setUp(org.testng.ITestContext)[pri:0, instance:com.QAproject.loginTest.LoginTest@5aa9e4eb]" started-at="2025-05-26T20:39:16 IST" name="setUp" finished-at="2025-05-26T20:39:19 IST" duration-ms="2889" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@5c77ba8f]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testLogin()[pri:0, instance:com.QAproject.loginTest.LoginTest@5aa9e4eb]" started-at="2025-05-26T20:39:19 IST" name="testLogin" finished-at="2025-05-26T20:39:32 IST" duration-ms="12707" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login failed expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login failed expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at com.QAproject.loginTest.LoginTest.testLogin(LoginTest.java:33)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:com.QAproject.loginTest.LoginTest@5aa9e4eb]" started-at="2025-05-26T20:39:32 IST" name="closeBrowser" finished-at="2025-05-26T20:39:32 IST" duration-ms="271" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="setUp(org.testng.ITestContext)[pri:0, instance:com.QAproject.loginTest.LoginTest@5aa9e4eb]" started-at="2025-05-26T20:39:32 IST" name="setUp" finished-at="2025-05-26T20:39:34 IST" duration-ms="1861" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@5c77ba8f]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testTitle()[pri:0, instance:com.QAproject.loginTest.LoginTest@5aa9e4eb]" started-at="2025-05-26T20:39:34 IST" name="testTitle" finished-at="2025-05-26T20:39:34 IST" duration-ms="119" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTitle -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:com.QAproject.loginTest.LoginTest@5aa9e4eb]" started-at="2025-05-26T20:39:34 IST" name="closeBrowser" finished-at="2025-05-26T20:39:34 IST" duration-ms="216" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- com.QAproject.loginTest.LoginTest -->
    </test> <!-- Login Tests -->
  </suite> <!-- Instagram Test Suite -->
</testng-results>
